/* Constantes puras do modelo de jogo — sem DOM, sem storage (regra A-LAYER do AGENTS.md). */

export const TM_CAT: Record<string, string> = {
  NORMAL: "PHYSICAL",
  GHOST: "SPECIAL",
  GRASS: "SPECIAL",
  POISON: "PHYSICAL",
  FIRE: "SPECIAL",
  FLYING: "PHYSICAL",
  WATER: "SPECIAL",
  ELECTRIC: "SPECIAL",
  PSYCHIC: "SPECIAL",
  GROUND: "PHYSICAL",
  FIGHTING: "PHYSICAL",
  ROCK: "PHYSICAL",
  ICE: "SPECIAL",
  BUG: "PHYSICAL",
  DARK: "PHYSICAL",
  DRAGON: "SPECIAL",
  FAIRY: "SPECIAL",
  STEEL: "PHYSICAL",
};

export const STAT_EXP: Record<string, number> = {
  hp: 0.95,
  atk: 0.8,
  def: 0.8,
  spAtk: 0.8,
  spDef: 0.8,
  speed: 0.8,
};

export const STAT_KEYS = ["hp", "atk", "def", "spAtk", "spDef", "speed"];

export const WILD_G = 16,
  WILD_Q = 1,
  WILD_HP_MULT = 5,
  WILD_DMG_MULT = 1.8;
export const DEF = { T0: 4.5, B: 0.49, Kp: 2.5, E: 0.8 };
export const DANGER_HPS = 0.5,
  CROWD_TAU = 10,
  CROWD_MAX = 3,
  VIP_XP = 1.5,
  EVENT_XP2 = 2,
  DAILY_TYPE_BONUS = 1.2;
/* Auto-Potion cura a partir de HP ≤ 60% por padrão; ajustável nas configurações */
export const DEF_AUTOPOT_THRESHOLD = 0.6;

/* espécies com versão "sem mapa" (área=null) que também têm uma versão marcada em Orre ou Nightmare com o mesmo nome —
   a versão sem mapa, nesses casos, não é do catálogo confirmado e não bateu com o mapa nos testes (Swampert, Makuhita, Whiscash, Sharpedo);
   mais um pequeno grupo listado como "no radar, ainda não implementado" no Discord oficial (24/09/2026) */
export const BUILTIN_HIDDEN = [
  "Abomasnow",
  "Absol",
  "Aegislash",
  "Aggron",
  "Altaria",
  "Appletun",
  "Archen",
  "Archeops",
  "Aron",
  "Bagon",
  "Baltoy",
  "Banette",
  "Barboach",
  "Bastiodon",
  "Beldum",
  "Blaziken",
  "Braviary",
  "Cacturne",
  "Camerupt",
  "Carracosta",
  "Carvanha",
  "Chandelure",
  "Claydol",
  "Combusken",
  "Corphish",
  "Cranidos",
  "Crawdaunt",
  "Dragalge",
  "Drampa",
  "Dusclops",
  "Duskull",
  "Eelektrik",
  "Eelektross",
  "Electrike",
  "Espurr",
  "Exploud",
  "Feebas",
  "Flabebe",
  "Floette",
  "Florges",
  "Flygon",
  "Gabite",
  "Gallade",
  "Garchomp",
  "Gardevoir",
  "Gible",
  "Glalie",
  "Gliscor",
  "Gogoat",
  "Goodra",
  "Goomy",
  "Grovyle",
  "Grumpig",
  "Infernape",
  "Kirlia",
  "Klang",
  "Klink",
  "Klinklang",
  "Lairon",
  "Lampent",
  "Larvesta",
  "Lilligant",
  "Litleo",
  "Litwick",
  "Lombre",
  "Lopunny",
  "Lotad",
  "Loudred",
  "Lucario",
  "Ludicolo",
  "Lunatone",
  "Luxray",
  "Magnezone",
  "Makuhita",
  "Manectric",
  "Mantyke",
  "Marshtomp",
  "Mawile",
  "Medicham",
  "Meditite",
  "Metang",
  "Mightyena",
  "Mismagius",
  "Mudkip",
  "Numel",
  "Nuzleaf",
  "Pachirisu",
  "Pancham",
  "Pangoro",
  "Pelipper",
  "Petilil",
  "Poochyena",
  "Ralts",
  "Rampardos",
  "Riolu",
  "Rockruff",
  "Rufflet",
  "Sableye",
  "Sandaconda",
  "Sawk",
  "Sceptile",
  "Scolipede",
  "Sealeo",
  "Seedot",
  "Seviper",
  "Sharpedo",
  "Shelgon",
  "Shieldon",
  "Shiftry",
  "Shuppet",
  "Silicobra",
  "Simisear",
  "Sirfetch'd",
  "Skiddo",
  "Skrelp",
  "Slakoth",
  "Sliggoo",
  "Smeargle",
  "Snorunt",
  "Solrock",
  "Spheal",
  "Spoink",
  "Swablu",
  "Swampert",
  "Swellow",
  "Taillow",
  "Throh",
  "Tirtouga",
  "Togekiss",
  "Torchic",
  "Torkoal",
  "Trapinch",
  "Treecko",
  "Tropius",
  "Turtonator",
  "Tynamo",
  "Venipede",
  "Vespiquen",
  "Vibrava",
  "Vigoroth",
  "Volcarona",
  "Walrein",
  "Weavile",
  "Whiscash",
  "Whismur",
  "Wingull",
  "Wormadam",
  "Zangoose",
];
